### ISSUE TITLE
Random number weirdness

### ISSUE THREAD

**Issue by Hunter-Github** [jweinst1/Oblivion#12]
### Steps to reproduce

* Run `oblivion`
* Enter `print(3!!4)` several times
* Get `6` at least once
* ...ask yourself `why?`

### Version

1.0.3

**Comment by jweinst1** [comment]
There was a bug in the combinations of `Math.floor()` and `Math.ceil()` that you need to use with `Math.random()` for this to work. Just fixed this and pushed a new version to NPM
