### ISSUE TITLE
Hello World program?

### ISSUE THREAD

**Issue by wolframroesler** [jweinst1/Oblivion#13]
Hi,

is there a simple Hello World program in Oblivion? I didn't find one in the docs.

Asking because I'm the maintainer of the Hello World Collection (http://helloworldcollection.de/) to which I'd like to add a Oblivion program.

Thanks!

**Comment by jweinst1** [comment]
Hi @wolframroesler 

So this is the github website that has the oblivion playground
https://jweinst1.github.io/OblivionWebsite/   You can see several examples there, and try out code yourself.

Oblivion has both a textual output and a visual output, so here is an example of a program that prints hello world and draws a small triangle

```
g = (1,8) *> (44, 9) *> (44,44)
draw g, print(hello World)
g = #red |= g
draw g
```

**Comment by jweinst1** [comment]
@wolframroesler did that example I gave you work ok? Can this be closed?

**Comment by wolframroesler** [comment]
Works, thanks!
