### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by raguay** [jweinst1/Oblivion#6]
This is my sequence on the command line:

~/test ➜ npm install -g oblivion-js
/usr/local/bin/oblivion -> /usr/local/lib/node_modules/oblivion-js/index.js
/usr/local/lib
└── oblivion-js@1.0.1

~/test ➜ oblivion test.obl
/usr/local/bin/oblivion: line 1: /Applications: is a directory
/usr/local/bin/oblivion: line 2: test.obl: command not found
/usr/local/bin/oblivion: line 3: */: No such file or directory
/usr/local/bin/oblivion: line 4: syntax error near unexpected token `('
/usr/local/bin/oblivion: line 4: `var cmp = require('./src/Main');'
~/test ⍉ ➜

The file test.obl is the red triangle example given on the website. Your trying to load a file with a relative path that doesn't exist in the installation directory: /usr/local/bin. 

I'm using macOS Siera latest beta. I followed the installation given on the website.

**Comment by jweinst1** [comment]
Was missing the `#! /usr/bin/env node` in the index file, all fixed now, and pushed a new version to NPM.
