### ISSUE TITLE
Command-line interactivity

### ISSUE THREAD

**Issue by Hunter-Github** [jweinst1/Oblivion#9]
A wish list:

* `--version` and `--help` command line switches
* an empty argument list should be treated gracefully, either by displaying help, or entering a REPL.

All in all, the utility looks v. promising. Thanks for sharing it with us!

EDIT: typo.

**Comment by jweinst1** [comment]
This is a good idea. All line and shape objects can be printed with `print()`, so a repl can definitively work as well.

**Comment by jweinst1** [comment]
Just added --version and --help to command line arguments. Will make the Repl then re-release on npm.

**Comment by jweinst1** [comment]
Ok, also released a new NPM version with a repl, and it comes up when you argue the package with no arguments.
